title: FlashStrike Documentation
description: High-performance Matching Engine Architecture

# Use Just the Docs via GitHub Pages
remote_theme: pages-themes/cayman@v0.2.0

# Optional: Configure Markdown & navigation
markdown: kramdown

search_enabled: true

# Collections (your docs folder)
collections:
  docs:
    output: true
    permalink: "/:collection/:path/"

just_the_docs:
  collections:
    docs:
      name: Documentation

